const PROFILE = {
  header: [
    "# Quantumult X 轻量分流配置",
    "# 更新日期：2026-05-28",
    "#",
    "# 配置目标：",
    "# - 这是本仓库默认推荐的一键订阅配置。",
    "# - 只启用分流规则，不启用 MITM、重写、解锁脚本、定时任务或响应体修改。",
    "# - 面向 iPhone 日常使用：优先保证稳定、可排查、低维护成本。",
    "#",
    "# 工作原理简述：",
    "# - [server_remote] 导入你的机场或自建节点订阅，需要替换示例链接。",
    "# - [policy] 定义可手动切换的策略组，规则会把流量交给这些策略组。",
    "# - [filter_remote] 导入上游规则集，决定域名或 IP 应该走哪个策略组。",
    "# - [filter_local] 优先级高于远程规则，适合放局域网、单独 IP 或临时修正规则。",
    "# - [rewrite_remote]、[rewrite_local]、[task_local]、[mitm] 默认留空，避免影响稳定性。",
  ],
  sections: [
    {
      name: "general",
      lines: [
        "# profile_img_url 是配置文件在 Quantumult X 中显示的图标。",
        "profile_img_url = https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Quantumult_X.png",
        "",
        "# network_check_url 用于检测当前网络是否可达。Apple 检测地址更贴近 iOS 系统网络环境。",
        "network_check_url = http://www.apple.com/library/test/success.html",
        "",
        "# server_check_url 和 server_check_timeout 用于测试节点延迟。",
        "server_check_url = http://www.gstatic.com/generate_204",
        "server_check_timeout = 3000",
        "",
        "# 复用 KOP-XIAO 的资源解析器。当远程资源设置 opt-parser=true 时，可转换兼容格式。",
        "# 本仓库不自建解析器，降低维护风险。",
        "resource_parser_url = https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js",
        "",
        "# dns_exclusion_list 可减少 fake-ip 对局域网、登录页、时间同步、微信、QQ 等场景的干扰。",
        "dns_exclusion_list = *.lan, *.local, *.msftconnecttest.com, *.msftncsi.com, stun.*, *.qq.com, localhost.*.qq.com, *.weixin.qq.com, pool.ntp.org, *.pool.ntp.org, time.*.com, time.*.apple.com",
        "",
        "# excluded_routes 让局域网、回环地址、运营商共享地址和组播地址绕过代理引擎。",
        "# 手机连接 AirDrop、投屏、打印机、NAS、路由器后台时通常需要这些直连规则。",
        "excluded_routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/24, 239.255.255.250/32",
      ],
    },
    {
      name: "dns",
      lines: [
        "# 轻量配置默认使用国内公共 DNS，便于国内 App、支付、地图和运营商网络保持稳定。",
        "# 默认不启用 DoH/DoH3，原因是加密 DNS 会增加排查难度，也可能被部分网络限制。",
        "server = 119.29.29.29",
        "server = 223.5.5.5",
        "server = 223.6.6.6",
        "",
        "# 最小化规避明显异常的 DNS 应答，避免复制难维护的大型污染 IP 列表。",
        "circumvent-ipv4-answer = 127.0.0.1, 0.0.0.0",
        "circumvent-ipv6-answer = ::",
        "",
        "# 官方示例默认启用 no-ipv6。移动网络 IPv6 质量不稳定时，关闭 AAAA 解析可减少直连超时。",
        "no-ipv6",
        "",
        "# 如果你所在网络 IPv6 可用且稳定，可以手动取消下面两行注释。",
        "# 如果你手动启用 IPv6 DNS，也建议同时注释 no-ipv6。",
        ";server = 2402:4e00::",
        ";server = 2400:3200::1",
      ],
    },
    {
      name: "policy",
      lines: [
        "# img-url 用于给策略组添加图标。Quantumult X 支持远程 PNG/JPG，也支持本地 Images 目录图标。",
        "# static 是手动选择策略组，适合新手；遇到某个服务不可用时，只需要切换对应服务组。",
        "",
        "# 主代理入口。proxy 是 Quantumult X 的通用代理出口；地区组用于按节点名称细分。",
        "# 日志中如果出现 No server for policy from remote server，优先切回 proxy 或检查地区正则。",
        "static = 出境代理, proxy, 香港节点, 新加坡节点, 台湾节点, 美国节点, 日本节点, 韩国节点, 其他地区, 直接连接, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Airport.png",
        "",
        "# 直接连接是系统直连出口，国内服务、局域网和私有域名默认走这里。",
        "static = 直接连接, direct, 出境代理, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Direct.png",
        "",
        "# 兜底策略。未命中任何规则的请求会走 Final；默认走代理，更适合需要稳定访问海外服务的用户。",
        "static = 兜底策略, 出境代理, 直接连接, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png",
        "",
        "# 日常服务策略组。每个服务独立分组，方便单独切换，不需要改整份配置。",
        "static = AI服务, 出境代理, proxy, 香港节点, 日本节点, 美国节点, 新加坡节点, 直接连接, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png",
        "static = 谷歌服务, 出境代理, proxy, 香港节点, 日本节点, 美国节点, 新加坡节点, 直接连接, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google.png",
        "static = GitHub服务, 出境代理, proxy, 香港节点, 日本节点, 美国节点, 新加坡节点, 直接连接, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/GitHub.png",
        "static = 海外社交, 出境代理, proxy, 香港节点, 日本节点, 美国节点, 新加坡节点, 直接连接, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png",
        "static = Telegram通讯, 出境代理, proxy, 香港节点, 新加坡节点, 日本节点, 美国节点, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png",
        "static = 微软服务, 直接连接, 出境代理, proxy, 香港节点, 日本节点, 美国节点, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png",
        "static = 苹果服务, 直接连接, 出境代理, proxy, 香港节点, 日本节点, 美国节点, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png",
        "static = 海外媒体, 出境代理, proxy, 香港节点, 新加坡节点, 台湾节点, 日本节点, 美国节点, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png",
        "static = 国内媒体, 直接连接, 出境代理, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/DomesticMedia.png",
        "static = 国内直连, 直接连接, 出境代理, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China.png",
        "static = 广告拦截, reject, 直接连接, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Advertising.png",
        "static = 劫持拦截, reject, 直接连接, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hijacking.png",
        "",
        "# 地区策略组按所有远程节点资源筛选，不依赖固定订阅名称，避免 tag 不一致导致地区组为空。",
        "# 如果你的机场节点没有地区关键词，直接使用 proxy 或在 Quantumult X 中手动选择具体节点。",
        "static = 香港节点, resource-tag-regex=.*, server-tag-regex=🇭🇰|香港|港|Hong Kong|HongKong|HK|hk, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png",
        "static = 新加坡节点, resource-tag-regex=.*, server-tag-regex=🇸🇬|新加坡|狮城|獅城|坡|Singapore|SG|sg, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png",
        "static = 台湾节点, resource-tag-regex=.*, server-tag-regex=🇹🇼|台湾|台灣|台北|Taiwan|Taipei|TW|tw, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Taiwan.png",
        "static = 美国节点, resource-tag-regex=.*, server-tag-regex=🇺🇸|美国|美國|美西|美东|United States|UnitedStates|USA|US|us|America|Los Angeles|Seattle|New York|San Jose, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png",
        "static = 日本节点, resource-tag-regex=.*, server-tag-regex=🇯🇵|日本|日|东京|大阪|Japan|Tokyo|Osaka|JP|jp, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png",
        "static = 韩国节点, resource-tag-regex=.*, server-tag-regex=🇰🇷|韩国|韓國|首尔|首爾|Korea|Korean|Seoul|KR|kr, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Korea.png",
        "static = 其他地区, resource-tag-regex=.*, server-tag-regex=🇬🇧|🇩🇪|🇫🇷|🇳🇱|🇮🇳|🇧🇷|🇦🇷|🇵🇭|🇻🇳|🇹🇭|🇮🇩|🇹🇷|🇷🇺|🇦🇺|🇨🇦|英国|英國|伦敦|倫敦|德国|德國|法国|法國|荷兰|荷蘭|印度|巴西|阿根廷|菲律宾|菲律賓|越南|泰国|泰國|印度尼西亚|印尼|土耳其|俄罗斯|俄羅斯|澳大利亚|澳洲|加拿大|United Kingdom|UK|Germany|DE|France|FR|Netherlands|NL|India|IN|Brazil|BR|Argentina|Philippines|Vietnam|Thailand|Indonesia|Turkey|Russia|Australia|Canada|CA, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png",
      ],
    },
    {
      name: "server_local",
      lines: ["# 默认留空。只有在你清楚 Quantumult X 本地节点完整语法时，才建议手动添加。"],
    },
    {
      name: "server_remote",
      lines: [
        "# 把下面的示例链接替换成你的真实节点订阅。",
        "# tag 是订阅资源名称，不再影响地区策略组筛选；地区组会按所有远程节点名称匹配。",
        ";https://example.com/your-subscription.snippet, tag=节点订阅, enabled=true, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Airport.png",
      ],
    },
    {
      name: "filter_local",
      lines: [
        "# 分流优先级是：[filter_local] > [filter_remote] > final。",
        "# 本地区块适合放临时修正、局域网直连、单独服务器 IP 分流。",
        "# 例：只让某台服务器走代理，可写 ip-cidr, 1.2.3.4/32, 出境代理。",
        "",
        "# 局域网和系统保留地址直连，避免影响 AirDrop、投屏、打印机、NAS、路由器后台和运营商网络。",
        "ip-cidr, 10.0.0.0/8, 直接连接",
        "ip-cidr, 100.64.0.0/10, 直接连接",
        "ip-cidr, 127.0.0.0/8, 直接连接",
        "ip-cidr, 172.16.0.0/12, 直接连接",
        "ip-cidr, 192.168.0.0/16, 直接连接",
        "ip-cidr, 224.0.0.0/24, 直接连接",
        "",
        "# final 必须放在最后。没有命中本地或远程规则的请求会交给兜底策略。",
        "final, 兜底策略",
      ],
    },
    {
      name: "filter_remote",
      lines: [
        "# 远程规则按顺序维护：拦截类优先，其次是具体服务，最后是自生成通用规则和宽泛的中国规则。",
        "# blackmatrix7 提供 Quantumult X 原生规则，默认不需要解析器转换，性能和兼容性更稳。",
        "# Loyalsoldier 通用规则由 GitHub Actions 转换后放在本仓库，配置直接引用 QuanX 格式结果。",
        "",
        "# 劫持和广告请求优先拒绝，减少无效连接、弹窗和运营商劫持干扰。",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Hijacking/Hijacking.list, tag=劫持拦截, force-policy=劫持拦截, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list, tag=广告拦截, force-policy=广告拦截, update-interval=86400, opt-parser=false, enabled=true",
        "",
        "# AI 服务集中到 AI 组，便于按节点地区和可用性单独调整。",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list, tag=OpenAI, force-policy=AI服务, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Claude/Claude.list, tag=Claude, force-policy=AI服务, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Gemini/Gemini.list, tag=Gemini, force-policy=AI服务, update-interval=86400, opt-parser=false, enabled=true",
        "",
        "# 常用海外服务。具体服务放在宽泛规则前面，便于排查和单独切换策略。",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Google/Google.list, tag=谷歌服务, force-policy=谷歌服务, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GitHub/GitHub.list, tag=GitHub服务, force-policy=GitHub服务, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Telegram/Telegram.list, tag=Telegram通讯, force-policy=Telegram通讯, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Microsoft/Microsoft.list, tag=微软服务, force-policy=微软服务, update-interval=86400, opt-parser=false, enabled=true",
        "",
        "# 社交应用覆盖日常高频场景，独立成组方便单独切换节点。",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Twitter/Twitter.list, tag=Twitter/X, force-policy=海外社交, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Facebook/Facebook.list, tag=Facebook, force-policy=海外社交, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Instagram/Instagram.list, tag=Instagram, force-policy=海外社交, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Discord/Discord.list, tag=Discord, force-policy=海外社交, update-interval=86400, opt-parser=false, enabled=true",
        "",
        "# 媒体规则。YouTube 是具体服务，GlobalMedia 是宽泛集合，所以 YouTube 放在前面。",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/YouTube/YouTube.list, tag=YouTube, force-policy=海外媒体, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GlobalMedia/GlobalMedia.list, tag=海外媒体, force-policy=海外媒体, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMedia/ChinaMedia.list, tag=国内媒体, force-policy=国内媒体, update-interval=86400, opt-parser=false, enabled=true",
        "",
        "# Apple 放在通用规则前，避免被宽泛补底规则过早接管。",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list, tag=苹果服务, force-policy=苹果服务, update-interval=86400, opt-parser=false, enabled=true",
        "",
        "# 本仓库自生成的 Loyalsoldier 通用规则。GFW 做海外补底，Private 保障私有域名直连。",
        "https://raw.githubusercontent.com/dolbyw/Rules-For-Quantumult-X/main/Rules/Generated/Loyalsoldier/GFW.list, tag=通用代理补充, force-policy=出境代理, update-interval=86400, opt-parser=false, enabled=true",
        "https://raw.githubusercontent.com/dolbyw/Rules-For-Quantumult-X/main/Rules/Generated/Loyalsoldier/Private.list, tag=私有域名直连, force-policy=直接连接, update-interval=86400, opt-parser=false, enabled=true",
        "",
        "# Direct 规则量较大，默认关闭。需要更强国内直连补底时再手动启用。",
        ";https://raw.githubusercontent.com/dolbyw/Rules-For-Quantumult-X/main/Rules/Generated/Loyalsoldier/Direct.list, tag=通用直连补充, force-policy=直接连接, update-interval=86400, opt-parser=false, enabled=false",
        "",
        "# ChinaMax 是 blackmatrix7 的国内域名/IP 大合集，放在末尾兜底国内直连。",
        "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMax/ChinaMax.list, tag=国内网站合集, force-policy=国内直连, update-interval=86400, opt-parser=false, enabled=true",
      ],
    },
    { name: "rewrite_local", lines: ["# 默认留空。重写会修改请求或响应，不属于轻量分流配置。"] },
    { name: "rewrite_remote", lines: ["# 默认留空。不启用远程去广告重写资源，降低 MITM 和脚本维护风险。"] },
    { name: "task_local", lines: ["# 默认留空。不启用定时脚本，避免后台耗电和不可控网络请求。"] },
    { name: "http_backend", lines: ["# 默认留空。纯分流配置不需要本地 HTTP 后端。"] },
    {
      name: "mitm",
      lines: [
        "# 默认留空。纯分流不需要 MITM。",
        "# 不要直接添加 hostname = *。只有明确需要某个重写功能时，再按域名最小化启用。",
      ],
    },
  ],
};

module.exports = PROFILE;
